version: '3.7'
services: 
  backend-service:
    image: ct-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: cashtracker-backend
    ports:
      - 5000:80
    depends_on: 
      - "db"

  frontend-service:
    image: ct-frontend
    ports: 
    - 3000:3000
    stdin_open: true
    container_name: cashtracker-frontend
    depends_on: 
      - "backend-service"

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Brewster_5
    volumes: 
      - ./Database/postgres_data:/var/lib/postgresql
      - ./Database/postgres.conf:/etc/postgresql/postgresql.conf
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    command: postgres -c config_file=/etc/postgresql/postgresql.conf
